### ISSUE TITLE
Errors with NC 15.0.2

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/bookmarks#651]
Hello,

I get, after upgrading from 14.0.6 to 15.0.2, some errors related to Bookmarks-App.

1. Cron Error
ArgumentCountError: Too few arguments to function OCA\Bookmarks\Lib\BackgroundJobs\PreviewsJob::__construct(), 0 passed in /var/www/clients/client39/web136/web/nc/lib/private/BackgroundJob/JobList.php on line 269 and exactly 7 expected
    /var/www/clients/client39/web136/web/nc/lib/private/BackgroundJob/JobList.php - line 269:
    OCA\Bookmarks\Lib\BackgroundJobs\PreviewsJob->__construct()
    /var/www/clients/client39/web136/web/nc/lib/private/BackgroundJob/JobList.php - line 213:
    OC\BackgroundJob\JobList->buildJob({ id: "853", ... "})
    /var/www/clients/client39/web136/web/nc/cron.php - line 117:
    OC\BackgroundJob\JobList->getNext()

2. PHP Error
Undefined index: host at /var/www/clients/client39/web136/web/nc/apps/bookmarks/controller/lib/previews/faviconpreviewservice.php#54

Thanks for fixing.

**Comment by marcelklehr** [comment]
This is fixed in v0.16.1 -- thanks for reporting! :)

**Comment by llucps** [comment]
Thanks!,

**Comment by llucps** [comment]
I just updated to 0.16.1 I checked the logs and still getting this error:

```
[cron] Error: TypeError: Argument 1 passed to OCA\Bookmarks\Lib\BackgroundJobs\PreviewsJob::__construct() must be an instance of OCA\Bookmarks\Lib\BackgroundJobs\IConfig, none given, called in /var/www/nextcloud/lib/private/BackgroundJob/JobList.php on line 269 at <<closure>>

0. /var/www/nextcloud/lib/private/BackgroundJob/JobList.php line 269
   __construct()
1. /var/www/nextcloud/lib/private/BackgroundJob/JobList.php line 213
   buildJob({id: "109",class ... "})
2. /var/www/nextcloud/cron.php line 117
   getNext()
```

**Comment by marcelklehr** [comment]
@llucps, that might be because the old BackgroundJob is still in the database. Can you perform the following SQL query on the database? `SELECT * from oc_jobs;`
If there are two entries that start with OCA\Bookmarks, delete the one with the lower id.

**Comment by llucps** [comment]
Done. There were 2 entries I deleted the one with the lower id as you said.
I'll let you know how it goes.

Thanks!

**Comment by llucps** [comment]
I guess it's not a big deal, but I'm getting this warning:

`[bookmarks] Warning: starting PreviewsJobp'

And right after I get this error:

`[no app in context] Error: Exception: Session has been closed - no further changes to the session are allowed at <<closure>>

 0. /var/www/nextcloud/lib/private/Session/Memory.php line 81
    validateSession()
 1. /var/www/nextcloud/apps/encryption/lib/Session.php line 179
    remove("publicSharePrivateKey")
 2. /var/www/nextcloud/apps/encryption/lib/Hooks/UserHooks.php line 190
    clear()
 3. /var/www/nextcloud/lib/private/legacy/hook.php line 106
    logout([])
 4. /var/www/nextcloud/lib/private/Server.php line 425
    emit("OC_User", "logout", [])
 5. <<closure>>
    OC\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php line 99
    call_user_func_array(Closure {}, [])
 7. /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php line 36
    emit("\\OC\\User", "logout", [])
 8. /var/www/nextcloud/lib/private/User/Session.php line 863
    emit("\\OC\\User", "logout")
 9. /var/www/nextcloud/apps/bookmarks/lib/BackgroundJobs/PreviewsJob.php line 52
    logout()
10. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
    run(null)
11. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
    execute(OC\BackgroundJob\JobList {}, OC\Log {})
12. /var/www/nextcloud/cron.php line 123
    execute(OC\BackgroundJob\JobList {}, OC\Log {})`

I forgot to mention that I'm using Nexctloud encryption.

Thanks,

**Comment by jknockaert** [comment]
I get the same error reported by @llucps above when the cron jobs runs. Also with encryption enabled.
